### ISSUE TITLE
Possible incompatibility with armor_monoid

### ISSUE THREAD

**Issue by jfmcbrayer** [EmptyStar/aerial#16]
On our server we've had aerial installed for a while, and added astralcraft. Unfortunately, it looks like armor_monoid, required by astralcraft, breaks featherfalling from aerial. I'm not sure what else to add to the report - this is on an Asuna server.

**Comment by EmptyStar** [comment]
This is definitely due to Aerial overriding the `fall_damage_add_percent` group that armor_monoid manages. I wrote Aerial a long time ago before I knew that armor_monoid existed and even today armor_monoid isn't very popular, so I really didn't foresee this situation.

I'll add an optional dependency to Aerial for armor_monoid and I'll make sure that it respects armor_monoid if it's present.

Thanks for reporting this!

**Comment by EmptyStar** [comment]
I just released v1.1.5 which has a compatibility fix for armor_monoid. I did my own testing to ensure that it works as expected with armor_monoid in Asuna, and with or without armor_monoid in Minetest Game, so this should fix it for you.

Thanks again and feel free to comment/reopen if this is still an issue for you.

**Comment by jfmcbrayer** [comment]
Very nice, thank you!

**Comment by jfmcbrayer** [comment]
Oops, I'm sorry to say this doesn't seem to solve it for me on my world... I'll try a more minimal test and let you know if it works there.

**Comment by EmptyStar** [comment]
Definitely make sure you've got the latest versions of Aerial and Armor Monoid, especially the latter since I updated it almost eight years (!) after the last commit and my changes are crucial to ensuring that the `fall_damage_add_percent` armor group is processed properly.

You could also check your mods for any mention of `fall_damage_add_percent` to see if any other mods might be interfering with it. When Armor Monoid is in use, any changes to the `fall_damage_add_percent` group outside of Armor Monoid will cause unpredictable results which is why Aerial was the culprit before I (supposedly) fixed it.

Also note that the feather falling is technically different from fall damage immunity. The feather falling effect is implemented by 3D Armor and it's the `armor_feather = 1` group that triggers this. However, lag can cause this effect to not work as designed and so I add fall damage immunity to make sure that players won't take damage even if they fall quickly due to lag. All that to say that if the feather falling effect isn't working then it's probably due to lag, but if the fall damage immunity isn't working, then it may be due to a mod incompatibility.

**Comment by jfmcbrayer** [comment]
That helps: I did a minimal test with a new world, and only aerial and armor_monoid enabled. Feather falling usually worked, but not always.... once in a while I'd fall fast and take damage. But I think I do not have the latest armor_monoid. Will check and test.

[later]
I updated armor_monoid to the tip of  https://github.com/minetest-mods/armor_monoid. It still seems to be the case that when feather falling fails because of lag, fall damage immunity does not kick in.

**Comment by EmptyStar** [comment]
OK, I'm able to reproduce in a minimal Minetest Game world. Let me see if I can figure out what's going on. I'll reopen this issue.

**Comment by EmptyStar** [comment]
Alright, I just published v1.1.6 and I believe it's actually fixed this time fr fr no cap. The issue was that I was missing `armor:register_armor_group("fall_damage_add_percent",100)` which registers the armor group with 3D Armor; without it, 3D Armor doesn't do any processing on the armor group.

This worked for me in my own testing, in a basic Minetest Game world with no mods enabled except for Aerial, 3D Armor, and Armor Monoid. I'm optimistic that it'll work as well for you!

**Comment by jfmcbrayer** [comment]
I can confirm that this works all the time. Thanks!

**Comment by EmptyStar** [comment]
Awesome! I'll go ahead and close out this issue for good then. Thanks so much for working with me to test the issue and confirm the fix. You're a real superstar for reporting issues on my repos and following up on comments and I'm always so grateful for all of your help!
